### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by amirnodehi** [olcf/mixed_cpu_gpu#1]
It does not work for me. I get the following when linking C with CUDA:

vecAddWrapperC.o: In function `vecAdd_wrapper':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0xc5): undefined reference to `sinf'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0xd7): undefined reference to `sinf'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x102): undefined reference to `cosf'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x114): undefined reference to `cosf'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x149): undefined reference to `cudaMemcpy'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x162): undefined reference to `cudaMemcpy'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x1d9): undefined reference to `cudaConfigureCall'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x213): undefined reference to `cudaMemcpy'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x289): undefined reference to `cudaFree'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x295): undefined reference to `cudaFree'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x2a4): undefined reference to `cudaFree'
vecAddWrapperC.o: In function `__cudaUnregisterBinaryUtil()':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x304): undefined reference to `__cudaUnregisterFatBinary'
vecAddWrapperC.o: In function `__nv_init_managed_rt_with_module(void**)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x31e): undefined reference to `__cudaInitModule'
vecAddWrapperC.o: In function `__device_stub__Z6vecAddPfS_S_i(float*, float*, float*, int)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x34d): undefined reference to `cudaSetupArgument'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x36e): undefined reference to `cudaSetupArgument'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x38f): undefined reference to `cudaSetupArgument'
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x3b0): undefined reference to `cudaSetupArgument'
vecAddWrapperC.o: In function `__nv_cudaEntityRegisterCallback(void**)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x46f): undefined reference to `__cudaRegisterFunction'
vecAddWrapperC.o: In function `__sti____cudaRegisterAll()':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x483): undefined reference to `__cudaRegisterFatBinary'
vecAddWrapperC.o: In function `cudaError cudaMalloc<float>(float**, unsigned long)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x4d1): undefined reference to `cudaMalloc'
vecAddWrapperC.o: In function `cudaError cudaLaunch<char>(char*)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text+0x4eb): undefined reference to `cudaLaunch'
vecAddWrapperC.o: In function `std::ceil(float)':
tmpxft_00025960_00000000-5_vecAddWrapperC.cudafe1.cpp:(.text._ZSt4ceilf[_ZSt4ceilf]+0x19): undefined reference to `ceilf'
collect2: error: ld returned 1 exit status

**Comment by AdamSimpson** [comment]
This tutorial covers compiling on the now decommissioned Titan system at ORNL.

**Comment by amirnodehi** [comment]
Thanks for your response.
Is there any way to do the same in a Linux system (gcc, nvcc)?
